### ISSUE TITLE
School, BasisGroup/ContactTeacherGroup/TeachingGroup not present in model

### ISSUE THREAD

**Issue by OlaStalberg** [FINTLabs/fint-betaling-model#11]
This requieres a change in what data the front end (https://github.com/FINTLabs/fint-betaling-frontend) sends to back end for it to be possible.

**Comment by torleifg** [comment]
If students/customers are added to the order in the context of a basis group etc. you need to know the names of all groups present in this order?

**Comment by OlaStalberg** [comment]
The frontend can register if a "group" is clicked, and if a group is clicked I could send that data in the order to the back end. The group name could then be present as a property in each of the customers. But this is not implemented hence the issue: https://github.com/FINTLabs/fint-betaling-frontend/issues/45
