### ISSUE TITLE
Claim should have Organisation

### ISSUE THREAD

**Issue by asgeirn** [FINTLabs/fint-betaling-model#8]
Claims should include the Organisation the claim is issued on behalf of.

**Comment by asgeirn** [comment]
Comments, @fsjovatsen, @torleifg ?

**Comment by torleifg** [comment]
From properties, or? Claims is also supposed to have User object with information on school owner and schools...

**Comment by asgeirn** [comment]
> 
> 
> From properties, or? Claims is also supposed to have User object with information on school owner and schools...

But what if User has access to several schools?

**Comment by torleifg** [comment]
> > From properties, or? Claims is also supposed to have User object with information on school owner and schools...
> 
> But what if User has access to several schools?

Hmm... then this should be sent as part of an Order from frontend?
